### ISSUE TITLE
Support SSL when SNI is in use

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik-mobile-2#5327]
Android: Dependent on this issue: https://jira.appcelerator.org/browse/TIMOB-17948
iOS: Not sure whether it already works here or not. If not it might automatically work by setting a TLS version: http://docs.appcelerator.com/titanium/3.0/#!/api/Titanium.Network.HTTPClient-method-setTlsVersion  not sure re any other drawbacks etc

**Comment by navhaxs** [comment]
Good news - Titanium SDK 4.1.0.GA has SNI SSL support implemented!

I was able to test Piwik Mobile on android with a Cloudflare SSL site after building with this newer SDK version. Note - needed to make changes as described in https://community.appcelerator.com/topic/2557/android-theme-windownoactionbar-throws-error-on-4-1-0-ga/2 due to SDK changes.

**Comment by masteranalyze** [comment]
Can piwik,release an new version,with this update,so we can have it all work?

https://github.com/piwik/piwik-mobile-2/issues/5348 ,basically cloudflare,is saying that piwik does not support the UNIVERSAL SSL from them,at least not on the free plan.

About this : Titanium SDK 4.1.0.GA ,can you explain how to install this on android or from where to get it?So we can make it work on our side.

At least on this time,i receive the same error,as Rican,after implementation with CLOUDFLARE free.

**Comment by tsteur** [comment]
Thx for this, that's great to hear! We might (haven't tested yet) need to release a new version because of the upcoming iOS 9 and Android 6 release anyway. Then we will update Titanium SDK 5.0

**Comment by Ricain** [comment]
Any news? Can we expect a 2.2.1 update with a SDK update?

**Comment by ecobux** [comment]
Great to hear you are working to solve this issue, thanks a lot! Any estimation when this new release will be out?

**Comment by tsteur** [comment]
Unfortunately not. I might find some time in the next weeks but I can't promise anything.

**Comment by tsteur** [comment]
Could yo try https://piwik.org/wp-content/uploads/2016/10/PiwikMobile2.3.0-b1.apk   maybe it fixes the issue.

**Comment by ecobux** [comment]
I installed it, but it crashes every time when I try to launch it (on Android 6.0.1, HTC). Actually, I think it even worked later with what I installed from Google Play.

**Comment by tsteur** [comment]
Sweet. I will close it in this case as it seems https://github.com/piwik/piwik-mobile-2/issues/5348#issuecomment-257420516 works now as well .

**Comment by ecobux** [comment]
So how do I fix now the broken app? Any chance to reinstall the working version without having to reinstall everything?

**Comment by tsteur** [comment]
Do you get any crash report when launching the app? 

You can download the latest version for Android (Piwik Mobile 2.2) from https://piwik.org/faq/mobile-app/faq_16330/ . This is the same as on Google Play.

 Sorry I thought you would uninstall & install the app from Google Play again. This should work but I am not sure if you would loose your configured account in between.

**Comment by ecobux** [comment]
Thanks, I will try that.

When launching the app, I just received the message:
"Unfortunately, Piwik Mobile 2 has stopped" with a "OK" button.

**Comment by xuhdev** [comment]
Since this is closed, the info [here](http://piwik.org/faq/mobile-app/#faq_19527) is then outdated.

**Comment by tsteur** [comment]
Thank you @xuhdev good point. I have updated it

**Comment by Luka5z88** [comment]
https://zapodaj.net/78ec1d24c807e.jpg.html
How to fix it?
