### ISSUE TITLE
Cloudflare SSL error: handshake failed

### ISSUE THREAD

**Issue by Ricain** [piwik/piwik-mobile-2#5348]
SSL handshake aborted... This website use Cloudflare free SSL.

![screenshot_2015-07-31-10-29-23](https://cloud.githubusercontent.com/assets/4070933/9005673/5fcf73b4-3780-11e5-9fea-168aed2b4bff.png)

Some issue that might be related: #5327, #5349 

**Config:**
- mobile: xperia SP
- os: android 4.4 (cm-11)
- app: piwik mobile 2 beta

**Comment by masteranalyze** [comment]
i have same problem,after i did put cloudflare free on my website.
How to fix this ?Any solutions?

**Comment by masteranalyze** [comment]
An official answer from Cloud Flare about this:

With regard to the error on Piwik, this looks like an SSL error. Your domain does have SSL set up and working so this likely means Piwik does not support the protocols CloudFlare uses for SSL. Universal SSL support is defined by the OS/Browser support for two newer features:

    Server Name Indication (SNI)
    Elliptic Curve certificates (ECDSA)

What browsers work with Universal SSL?

What cipher suites does CloudFlare use for SSL?

If you need broader browser compatibility for older browsers/operating systems, our Pro plan plan provides this.

Also, if you want to get full information about what your browser supports, this site will run a check on your browser and tell you the support your browser has for protocols, ciphers and SNI:

https://cc.dcsec.uni-hannover.de/

So the question is now : Piwik will support the protocols CloudFlare uses for SSL ,so we can login into the mobile application ?

I did not understood exactly,if an upgrade to the Pro Plan on Cloudflare,will make the PIWIK mobile,working!But i will ask,and come back with their answer.

**Comment by mattab** [comment]
This will be fixed in  #5327

**Comment by masteranalyze** [comment]
Great to hear that Matt,any ideea practically,when we will have an new version in android for piwik mobile,with this fixed?Aproximatelly of course.

Thank you Matt!

**Comment by Ricain** [comment]
@mattab thank :)

**Comment by endrepalinkas** [comment]
I get this error too, with a Cloudflare SSL cert on the domain.

**Comment by tsteur** [comment]
Could yo try https://piwik.org/wp-content/uploads/2016/10/PiwikMobile2.3.0-b1.apk   maybe it fixes the issue.

**Comment by Ricain** [comment]
@tsteur since this issue was open I switched phone and I am now on Android 6 and, for some reasons, the Piwik app on Google's PlayStore works with CloudFlare.

I tried your linked APK, it works too with my new Xperia Z5 Compact. I will try with my old phone during Christmas holidays.

Thanks for the work done 👍

**Comment by tsteur** [comment]
Thanks for the feedback 👍
