### ISSUE TITLE
Test app with Android 6.0 (Marshmallow) and iOS 9

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik-mobile-2#5350]
Google announced today the next Android version which will be available probably in fall 2015. We should test it upfront to make sure everything still works

**Comment by tsteur** [comment]
There will be a Titanium 5.0 release supporting iOS9 and Android 6.0. We might have to make the app compatible with Titanium 5.0

**Comment by tsteur** [comment]
FYI: I tried to test the app on the iOS 9.0 Simulator but this was only possible by using a nightly build of Titanium SDK 5.0.0. We're currently using Titanium SDK 3.4.1 and it's not compatible with latest Xcode. Maybe someone has an Apple device running iOS 9.0 and can install and try the app? @mattab maybe  we can ask users in a tweet whether someone is using the app under iOS 9.0?

I ran the app with a beta of Titanium SDK 5.0 under iOS 9 beta but it doesn't even show me an alert or a window or anything after logging in.

**Comment by tsteur** [comment]
I will try to install iOS 9 on my iPod touch but this might take a while in case it works

**Comment by tsteur** [comment]
I updated my iPod touch to latest iOS 9 beta and tested with current Piwik Mobile 2. I clicked on pretty much every button and seems to be working fine so far. The only thing that I noticed were misplaced icons in visitor log and live visitors:

![screen shot 2015-08-27 at 22 21 27](https://cloud.githubusercontent.com/assets/273120/9532366/8aa08e02-4d0b-11e5-8172-09874ae9a81f.png)
![screen shot 2015-08-27 at 22 22 00](https://cloud.githubusercontent.com/assets/273120/9532367/8aabb11a-4d0b-11e5-93df-b7faaf942eef.png)

we should test again shortly before the final iOS 9 will be available. I'm not sure if the misplaced icons are worth the effort of updating to Titanium SDK 5.0 which can be quite a bit of work.

**Comment by tsteur** [comment]
Android 6.0 will be released next week. I haven't had the time to install it yet. Has maybe someone noticed some issues?

**Comment by tsteur** [comment]
I just installed Android 6.0 on a Nexus 7 and it works just fine. Runs super fast and only thing I noticed was the range selector was a bit misplaced when selecting period = range see screenshot.

![screenshot_20151005-200958](https://cloud.githubusercontent.com/assets/273120/10289252/b7ce68d0-6b9d-11e5-8e0b-b82cee607b09.png)

**Comment by mattab** [comment]
awesome to hear Piwik Mobile works so well with recent smartphones! :+1:
