### ISSUE TITLE
Segment not applied to sub-reports?

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik-mobile-2#5353]
From a user feedback:

> I'm in pageviews section. The root page show me the total of view accordingly to the segment I choose. It works. But when I click on one sub page, it's seem to be for all data.
> I forgot some details. I'm in Report.. then Page url... then Pageviews... then detail in one page.

Needs investigation

**Comment by 188881** [comment]
www.bulentozalp.com i think.
