### ISSUE TITLE
No line graphs since upgrade to Piwik 3.0

### ISSUE THREAD

**Issue by fvdm** [piwik/piwik-mobile-2#5364]
Since I upgraded my Piwik to 3.0 the iOS app won't generate the line graphs anymore, even though there is enough data available to graph.

Piwik Mobile 2.3.0
Piwik 3.0.0
iOS 10.2

![piwik mobile](https://d.pr/i/Myvf/1G4yZBPN+)

**Comment by tsteur** [comment]
This seems to be a problem in Piwik. I recommend to have a look here https://github.com/piwik/piwik/issues/11075

**Comment by fvdm** [comment]
I don't see how that is related, I have only PHP v7.1 and the entire Piwik instance is running fine. Only the Piwik Mobile app is acting up.
