### ISSUE TITLE
Graphs do not display on android when gzip is on in nginx configuration.

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik-mobile-2#5365]
Feedback from a user. Need to investigate.

**Comment by Findus23** [comment]
I'm not sure if gzip is at fault. I am using nginx and the graphs work in the android app.
Normally nginx doesn't gzip images (which wouldn't make sense, as they don't compress well).
But even if I enable gzip for images the graphs still load.

**Comment by tsteur** [comment]
OK thanks. I will close the issue as I thought as well it shouldn't be related 👍
