### ISSUE TITLE
Cannot display campaign name report

### ISSUE THREAD

**Issue by mgonera** [piwik/piwik-mobile-2#5366]
Hello, I encountered issue where after choosing "more" in campaign names table and choosing specific element (with arrow ">" on the right) there is an error:

![ios_error](https://cloud.githubusercontent.com/assets/11424829/22369832/87df989a-e48e-11e6-9f6a-4f3e00b2d53c.png)

**Comment by tsteur** [comment]
That must be an error in the report / plugin itself as it is working fine for other reports. Closing as it is very likely not related to piwik mobile

**Comment by mgonera** [comment]
@tsteur requesting the same dataset in the UI works flawlessly:

<img width="554" alt="screen shot 2017-01-27 at 22 17 21" src="https://cloud.githubusercontent.com/assets/11424829/22387961/655646b6-e4de-11e6-8eae-2cacc0d0066f.png">

**Comment by tsteur** [comment]
Yes, I presume the metadata or so is not configured correctly. Piwik reports don't use the API

**Comment by mgonera** [comment]
what metadata you mean? where is the problem in this case?

**Comment by mgonera** [comment]
ping @tsteur how that may be not an issue with mobile app? I checked separate 3 instances

**Comment by tsteur** [comment]
Report Metadata etc. It works for all other reports so I'm pretty certain the report is not configured properly

**Comment by mattab** [comment]
The metadata in the report itself or. In piwik core or specific plugin
creating the repory

**Comment by mgonera** [comment]
Thanks for the tip, I will try to find out more!

28.01.2017 04:24 "Matthieu Aubry" <notifications@github.com> napisał(a):
