### ISSUE TITLE
App seems to cache icons randomly

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik-mobile-2#5370]
While testing all icon changes, I often notice that the app seems to cache them. I often see some new and old icons next to each other.

e.g I wanted to test the new flags, so I added my local piwik instance to the app. Even though I have never added this IP before the app shows the old flags (but just on iOS, Android is fine)
Is it possible that the app is caching them even between account (and servers)? How long are they cached?

**Comment by tsteur** [comment]
This is all done by the underlying framework and Android. It should cache it depending on the HTTP cache headers AFAIK. There is not really anything we can change as it is really just passing an URL to the Android image view in our framework. I would presume they shouldn't be cached between servers but if they do, it wouldn't even be too bad as they usually rarely change. I'll close it for now but when I notice an option re the caching becomes ever available I will look into it again.
