### ISSUE TITLE
thin border around flags

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik-mobile-2#5371]
Followup to https://github.com/piwik/piwik/pull/11553

Because the new flags aren't glossy, flags with white stripes (e.g. Russia are looking a bit odd).
In piwik we solved this by adding a small dark border around them.

Is it possible to do the same in the app?

![screenshot_20170330-075353](https://cloud.githubusercontent.com/assets/6266037/24489848/eda63d16-151f-11e7-8054-692bd63a4f62.png)

**Comment by tsteur** [comment]
That should be possible. I'm adding it to the next milestone. They look great there otherwise BTW. Good work 👍
