### ISSUE TITLE
Can't access piwik via https:// from Android 7 ("java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.")

### ISSUE THREAD

**Issue by blu-IT** [piwik/piwik-mobile-2#5375]
Hello,

with my new phone (Android 7) I can't access/configure my Piwik mobile app to connect to my piwik server via https://

I get the message:

```
Network error
There was an error "java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.". The request returned the status "0". URL was "https://piwik.myserver.org/index.php". Please check your entered URL and the error logs on this server for more information about the error and how to resolve it. 
```
I guess the problem maybe is my "self-signed" certificate on the server? But with other devices (Android 4) it is no problem. I already imported the certificate into my new phone, but it still doesn't connect to my piwik instance.

Any help appreciated!

Regards,

**Comment by tsteur** [comment]
The app does not work with self-signed certificates anymore unfortunately. Google pretty much required developers to eg not offer an option to ignore SSL errors. 

When you got your new phone with new Android version, did you maybe also install a newer Piwik Mobile version? It is also possible that Android used to handle it differently. 

The only thing I can think of, would be to try an older Piwik Mobile version eg 2.2.0 (or maybe 2.3.0) from here: https://piwik.org/faq/mobile-app/faq_16330/
