### ISSUE TITLE
Check all icons are on the left and change if not

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik-mobile-2#5377]
In case https://github.com/piwik/piwik/issues/12301 will be implemented and icons will be actually moved to the left, it would be great to investigate whether in the mobile app all icons are on the left as well, or whether it makes sense to move them to the left etc for consistent look & feel.

**Comment by Findus23** [comment]
I quickly checked the android version and the only place where I could icons next to text is the right sidebar:
<img src="https://user-images.githubusercontent.com/6266037/33243494-a923eb9e-d2e7-11e7-859c-54a4367adf7c.png" width="350">

**Comment by tsteur** [comment]
![image](https://user-images.githubusercontent.com/273120/34290913-a00d7fa8-e75e-11e7-94f9-1e09b6f5b1e1.png)

Just implemented it but I think it looks better on the right and maybe we can actually close the issue again. @Findus23 feel free to reopen if you have any preference on the position.
